### ISSUE TITLE
call_history file malformed

### ISSUE THREAD

**Issue by ARIFJEZIR** [jsharkey13/iphone_backup_decrypt#1]
call_history.sqlite -> file was not open sqlite db

**Comment by jsharkey13** [comment]
Is it a recent encrypted backup, created from iOS13 by iTunes on Windows? Is the decryption password definitely correct (i.e. try an invalid password just to check you do see an error)? How did you verify the SQLite file was malformed?

You could also try these projects, which are also copies of the underlying Google library:
https://github.com/avibrazil/iOSbackup (Python)
https://github.com/garrett-davidson/iOS-Backup-Forensics-Toolkit (Swift)

**Comment by jsharkey13** [comment]
@ARIFJEZIR; I think I have reproduced this issue and fixed it. If you try using the latest version from GitHub, do you still have the same issue?

**Comment by jsharkey13** [comment]
I believe this is now fixed. Please re-open with more details if not.

**Comment by ARIFJEZIR** [comment]
Thanks it's working!!!!!

**Comment by ARIFJEZIR** [comment]
Thanks it's working!!!!!
