### ISSUE TITLE
the extracted call_history.sqlite, sms.db database still needs password to open

### ISSUE THREAD

**Issue by andy380743909** [jsharkey13/iphone_backup_decrypt#6]
the decrypted manifest.db can be open directly, and extracted cameraroll videos can play normally, but the extracted call_history.sqlite, sms.db database needs password to open.

do you know what's the password, or how to generate it? 

Thank you!

**Comment by andy380743909** [comment]
iOS Version: 14.5
macOS Version: 11.5

**Comment by andy380743909** [comment]
I am sorry, it turns out to be the file permission issue, after I fix the permission issue, the sqlite db file can be opened successfully.
Thanks for this cool project again !

**Comment by jsharkey13** [comment]
Ah, I am glad this did work for you. I'd not had time to check it, but I knew it had worked on iOS 14 and 15 backups for me.
